<?xml version="1.0" encoding="ISO-8859-15"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:variable name="LBL.ACTION">Action</xsl:variable>
	<xsl:variable name="LBL.ACTIONS">Actions</xsl:variable>
	<xsl:variable name="LBL.AFFICHER">Afficher</xsl:variable>
	<xsl:variable name="LBL.ANNEE">Année</xsl:variable>
	<xsl:variable name="LBL.ANNEES">Années</xsl:variable>
	<xsl:variable name="LBL.CLE">Clé</xsl:variable>
	<xsl:variable name="LBL.COMPTE">Compte</xsl:variable>
	<xsl:variable name="LBL.COMPTEDESTINATION">Compte destination</xsl:variable>
	<xsl:variable name="LBL.COMPTEPRINCIPAL">Compte principal</xsl:variable>
	<xsl:variable name="LBL.COMPTES">Comptes</xsl:variable>
	<xsl:variable name="LBL.CREERNOUVEAU">Créer un nouveau @1</xsl:variable>
	<xsl:variable name="LBL.CREEROPERATION">Créer une nouvelle @1</xsl:variable>
	<xsl:variable name="LBL.CREDIT">Crédit</xsl:variable>
	<xsl:variable name="LBL.CREER">Créer</xsl:variable>
	<xsl:variable name="LBL.DATE">Date</xsl:variable>
	<xsl:variable name="LBL.DEBIT">Débit</xsl:variable>
	<xsl:variable name="LBL.DECONNEXION">Déconnexion</xsl:variable>
	<xsl:variable name="LBL.DEPENSE">Dépense</xsl:variable>
	<xsl:variable name="LBL.DEPENSES">Dépenses</xsl:variable>
	<xsl:variable name="LBL.DERNIEREANNEE">Dernière année</xsl:variable>
	<xsl:variable name="LBL.DERNIERMOIS">Dernier mois</xsl:variable>
	<xsl:variable name="LBL.DERNIERRELEVE">Dernier relevé</xsl:variable>
	<xsl:variable name="LBL.DESCRIPTION">Description</xsl:variable>
	<xsl:variable name="LBL.DETAILFLUX">Détail flux</xsl:variable>
	<xsl:variable name="LBL.DIFFERENCE">Difference</xsl:variable>
	<xsl:variable name="LBL.EDITER">Editer</xsl:variable>
	<xsl:variable name="LBL.EDITIONCOMPTE">Edtion compte</xsl:variable>
	<xsl:variable name="LBL.EDITIONLISTEPREVISION">Edtion liste prévisions</xsl:variable>
	<xsl:variable name="LBL.EDITIONPREVISION">Edtion d'une prévision</xsl:variable>
	<xsl:variable name="LBL.EDITIONFLUX">Edtion d'un flux</xsl:variable>
	<xsl:variable name="LBL.EDITIONOPERATION">Edtion d'une opération</xsl:variable>
	<xsl:variable name="LBL.EDITIONSEGMENT">Edtion d'un segment</xsl:variable>
	<xsl:variable name="LBL.ENTETE">Entête</xsl:variable>
	<xsl:variable name="LBL.ENTREEEPARGNE">Entrée épargne</xsl:variable>
	<xsl:variable name="LBL.ENREGISTRER">Enregistrer</xsl:variable>
	<xsl:variable name="LBL.EQUILIBRER">Equilibrer</xsl:variable>
	<xsl:variable name="LBL.EPARGNE">Epargne</xsl:variable>
	<xsl:variable name="LBL.ESTIMATION">Estimation</xsl:variable>
	<xsl:variable name="LBL.FERMER">Fermer</xsl:variable>
	<xsl:variable name="LBL.FLUX">Flux</xsl:variable>
	<xsl:variable name="LBL.FLUXMAITRE">Flux maitre</xsl:variable>
	<xsl:variable name="LBL.INTEGRATION">Intégration</xsl:variable>
	<xsl:variable name="LBL.INTERPRETEURSQL">Interpréteur SQL</xsl:variable>
	<xsl:variable name="LBL.LISTEDESCOMPTES">Liste des comptes</xsl:variable>
	<xsl:variable name="LBL.LIBCOURT">Libellé court</xsl:variable>
	<xsl:variable name="LBL.LIBELLE">Libellé</xsl:variable>
	<xsl:variable name="LBL.LIBLONG">Libellé long</xsl:variable>
	<xsl:variable name="LBL.LISTEFLUX">Liste des flux</xsl:variable>
	<xsl:variable name="LBL.LISTEOPERATION">Liste des opérations</xsl:variable>
	<xsl:variable name="LBL.LOGIN">Login</xsl:variable>
	<xsl:variable name="LBL.MENUSEG">Clé;libelllé court;libellé long;ordre;</xsl:variable>
	<xsl:variable name="LBL.MODEDEPAIEMENT">Mode de règlement</xsl:variable>
	<xsl:variable name="LBL.MODEDEPAIEMENTDEF">Mode de paiement par défaut</xsl:variable>
	<xsl:variable name="LBL.MODIFIER">Modifier</xsl:variable>
	<xsl:variable name="LBL.MOIS">Mois</xsl:variable>
	<xsl:variable name="LBL.MONTANT">Montant</xsl:variable>
	<xsl:variable name="LBL.MOTDEPASSE">Mot de passe</xsl:variable>
	<xsl:variable name="LBL.NBMOIS">Nombre mois</xsl:variable>
	<xsl:variable name="LBL.NOM">Nom</xsl:variable>
	<xsl:variable name="LBL.NON">Non</xsl:variable>
	<xsl:variable name="LBL.NORELEVE">No relevé</xsl:variable>
	<xsl:variable name="LBL.NOUVEAU">Nouveau</xsl:variable>
	<xsl:variable name="LBL.NUMEROCOMPTE">Numéro de compte</xsl:variable>
	<xsl:variable name="LBL.NUMERORELEVE">Numéro de relevé</xsl:variable>
	<xsl:variable name="LBL.OPERATION">Opération</xsl:variable>
	<xsl:variable name="LBL.OPERATIONS">Opérations</xsl:variable>
	<xsl:variable name="LBL.OUI">Oui</xsl:variable>
	<xsl:variable name="LBL.PARAMETRAGE">Paramétrage</xsl:variable>
	<xsl:variable name="LBL.PERIODE">Période</xsl:variable>
	<xsl:variable name="LBL.PERIODICITE">Périodicité</xsl:variable>
	<xsl:variable name="LBL.PREMIERRELEVE">Premier relevé</xsl:variable>
	<xsl:variable name="LBL.PREMIEREANNEE">Première année</xsl:variable>
	<xsl:variable name="LBL.PREMIERMOIS">Premier mois</xsl:variable>
	<xsl:variable name="LBL.PRENOM">Prénom</xsl:variable>
	<xsl:variable name="LBL.PREVISIONS">Prévisions</xsl:variable>
	<xsl:variable name="LBL.PREVISIONSCOMPTE">Prévisions du compte</xsl:variable>
	<xsl:variable name="LBL.PROPAGER">Propager</xsl:variable>
	<xsl:variable name="LBL.RECETTE">Recette</xsl:variable>
	<xsl:variable name="LBL.RECETTES">Recettes</xsl:variable>
	<xsl:variable name="LBL.RETOURALALISTE">Retour à la liste</xsl:variable>
	<xsl:variable name="LBL.RETOURCOMPTE">Retour au compte</xsl:variable>
	<xsl:variable name="LBL.SAISIEAUTRE">Saisie autre opération</xsl:variable>
	<xsl:variable name="LBL.SECONNECTER">Se connecter</xsl:variable>
	<xsl:variable name="LBL.SEGMENT">Segment</xsl:variable>
	<xsl:variable name="LBL.SOLDEBASE">Solde de base</xsl:variable>
	<xsl:variable name="LBL.SORTIEEPARGNE">Sortie épargne</xsl:variable>
	<xsl:variable name="LBL.SOLDE">Solde</xsl:variable>
	<xsl:variable name="LBL.STATISTIQUES">Statistiques</xsl:variable>
	<xsl:variable name="LBL.STATUT">Statut</xsl:variable>
	<xsl:variable name="LBL.STATUTMAITRE">Statut maitre</xsl:variable>
	<xsl:variable name="LBL.STATUTS">Statuts</xsl:variable>
	<xsl:variable name="LBL.SYNTHESE">Synthèse</xsl:variable>
	<xsl:variable name="LBL.TITRE">Titre</xsl:variable>
	<xsl:variable name="LBL.TOTAL">Total</xsl:variable>
	<xsl:variable name="LBL.TOTALCREDITS">Total crédits</xsl:variable>
	<xsl:variable name="LBL.TOTALDEBITS">Total débits</xsl:variable>
	<xsl:variable name="LBL.TOTALDEPENSES">Total dépenses</xsl:variable>
	<xsl:variable name="LBL.TOTALPREVISIONS">Total prévisions</xsl:variable>
	<xsl:variable name="LBL.TOTALRECETTES">Total recettes</xsl:variable>
	<xsl:variable name="LBL.VALIDER">Valider</xsl:variable>
	<xsl:variable name="LBL.VERIFICATION">Vérification</xsl:variable>
	<xsl:variable name="LBL.VISUALISER">Visualiser</xsl:variable>
</xsl:stylesheet>
